### ISSUE TITLE
Week3 - Complete experiment 4

### ISSUE THREAD

**Issue by appuCoding** [gx72xk/Cs5610-Kai-Xiang#2]
Week3 -  Complete experiment 4

**Comment by gx72xk** [comment]
Sorry I didn't understand....

**Comment by appuCoding** [comment]
you did only 3 experiments , Its mandatory that you complete all 5 experiments , so added one issue for experiment 4 and one issue for experiment 5.

**Comment by gx72xk** [comment]
I just combined some of the experiments in one page , i didn't know that we have to do single page experiment, but I ll be doing this later
