### ISSUE TITLE
Write Blog every week and add it to the GIT. -week8

### ISSUE THREAD

**Issue by appuCoding** [gx72xk/Cs5610-Kai-Xiang#34]
Write Blog every week and add it to the GIT. -week8

**Comment by gx72xk** [comment]
Sorry my computer was down for the week , It just got back to work, I ll do all the blog and the experiments this week.
Sorry for that

**Comment by appuCoding** [comment]
You need to add blogs to GIT which you didnt do. Please do it and then Close it
