### ISSUE TITLE
Week3 , Description about experiments

### ISSUE THREAD

**Issue by appuCoding** [gx72xk/Cs5610-Kai-Xiang#5]
Give the description about experiments

**Comment by gx72xk** [comment]
I will add descriptions. Is it fine fine that I do several experiments in one page?

**Comment by appuCoding** [comment]
No you shouldn't do several experiments in one page.

One page = one experiment .

**Comment by gx72xk** [comment]
but I already did it in the last 5 experiments.....I'll do it this way from next time, can i?

**Comment by appuCoding** [comment]
Please change as mentioned above , else it may effect your grade, Professor expects 5 experiments per week.
